var deviceType=window.matchMedia("only screen and (max-device-width: 640px)").matches?"mobile":"desktop",childDiv,childTabs=[],childWindows=[],childWindowsTabs=new Map;
window.addEventListener("message",function(a){var b=childWindowsTabs.get(a.source);if(b)if("wm."===a.data.action.substr(0,3)){if("wm.focus"!==a.data.action)if("wm.reportClicked"===a.data.action)apps.classList.remove("shown"),powerMenu.classList.remove("shown");else if("wm.setTitle"===a.data.action)a=a.data.args[0]||getName(b.manifest),b.tabtitlebar.querySelector(".title").textContent=b.title=a,b.querySelector("iframe").name=a,b.classList.contains("focused")&&airborn.core.setTitle(a),updateDummyTabs();
else if("wm.setIcon"!==a.data.action&&"wm.openFile"!==a.data.action)if("wm.openWindow"===a.data.action)window.openTab.apply(window,a.data.args);else if("wm.showProgress"===a.data.action||"wm.setProgress"===a.data.action||"wm.hideProgress"===a.data.action)b={loaderElm:b.tabtitlebar.querySelector(".loader")},window[a.data.action.substr(3)].apply(window,a.data.args.concat(b));else throw"unknown action";}else throw"unknown action";},!1);
showProgress=function(a){a.loaderElm&&(a.loaderElm.progressFrac=0,setProgress(.1,a))};setProgress=function(a,b){!b.loaderElm||b.loaderElm.progressFrac>=a||(b.loaderElm.style.backgroundColor="rgba(77, 164, 213, .5)",b.loaderElm.style.width=100*a+"%",b.loaderElm.progressFrac=a)};hideProgress=function(a){a.loaderElm&&(a.loaderElm.style.width="")};
getName=function(a){var b;a.locales&&(navigator.languages||[navigator.language]).some(function(c){return b=a.locales[c]&&a.locales[c].name||c===a.default_locale&&a.name});return b||a.name};var appIconSize=("mobile"===deviceType?32:64)*(window.devicePixelRatio||1);getIconUrl=function(a){if(a)return a[Object.keys(a).sort(function(a,c){return a>=appIconSize&&c>=appIconSize?a-c:c-a})[0]]};
openWindow=function(){var a=document.createElement("div");a.className="window";var b=document.createElement("div");b.className="titlebar";a.appendChild(b);var c=document.createElement("div");c.className="tabs";a.appendChild(c);c=document.createElement("div");c.className="tabbar";c.addEventListener("mousedown",function(a){a.stopPropagation()});b.appendChild(c);c=document.createElement("div");c.textContent="+";c.className="addtab";c.addEventListener("click",function(){openTab(a.querySelector(".tab.focused").path)});
b.appendChild(c);document.body.appendChild(a);childDiv=a};
openTab=function(a,b){b||(b={});var c=childDiv,f=c.querySelector(".tabs"),d=document.createElement("div");d.className="tab";f.appendChild(d);d.path=a;var g=c.querySelector(".tabbar"),e=document.createElement("div");e.className="tabtitlebar";e.addEventListener("mousedown",function(){switchTab(e.tab)});e.addEventListener(navigator.userAgent.includes("Firefox")?"click":"mousedown",function(a){focusTab(e.tab);a.preventDefault()});e.tab=d;d.tabtitlebar=e;g.insertBefore(e,b.after&&b.after.tabtitlebar.nextSibling);
childTabs.splice(b.after?childTabs.indexOf(b.after)+1:childTabs.length,0,d);airborn.fs.getFile(a+"manifest.webapp",function(c){c=c?JSON.parse(c.replace(/^\uFEFF/,"")):{};var f=document.createElement("img");f.className="icon";var h=getIconUrl(c.icons);h&&airborn.fs.prepareUrl(h,{relativeParent:a,rootParent:a},function(a){f.src=a});e.appendChild(f);h=document.createElement("span");h.className="title";h.textContent=d.title=getName(c);e.appendChild(h);h=document.createElement("div");h.className="loader";
e.appendChild(h);d.manifest=c;d.dummy=b.dummy;updateDummyTabs();b.dummy?e.addEventListener("mousedown",function(){d.tabtitlebar.style.display="none";openTab(a,{after:d})}):(loadTab(a,b,d),switchTab(d),b.after||(g.scrollLeft=g.scrollWidth,f.addEventListener("load",function(){g.scrollLeft=g.scrollWidth})),airborn_localStorage.lastApp=a)})};
function loadTab(a,b,c){var f=c.manifest,d=f.launch_path?f.launch_path.replace(/^\//,""):a.match(/[^/]+(?=\/$)/)[0]+".html",d=a+d,g=a.replace("Apps","AppData"),e=f.csp||"default-src *; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'",e=-1!==e.indexOf("-src ")?e.replace(/-src /g,"-src data: "):"default-src data:; "+e,k={apps:"/Apps/",music:"/Music/",pictures:"/Pictures/",sdcard:"/Documents/",system:"/Core/",videos:"/Videos/"},l=(d.match("/Apps/(.+?)/")||[])[1],l={read:[a,g].concat(Object.keys(f.permissions||
{}).filter(function(a){return k[a.replace("device-storage:","")]&&-1!==["readonly","readwrite","readcreate"].indexOf(f.permissions[a].access)}).map(function(a){return k[a.replace("device-storage:","")]})),write:[g].concat(Object.keys(f.permissions||{}).filter(function(a){return k[a.replace("device-storage:","")]&&-1!==["readwrite","readcreate","createonly"].indexOf(f.permissions[a].access)}).map(function(a){return k[a.replace("device-storage:","")]})),manageApps:(f.permissions||{})["webapps-manage"],
appName:l,urlArgs:l,getObjectLocations:(f.permissions||{})["get-object-locations"]};airborn.fs.prepareUrl(b.path||"/",{rootParent:a,relativeParent:d,permissions:l,csp:e,appData:g},function(b){var d=document.createElement("iframe");d.sandbox="allow-scripts allow-forms allow-popups allow-modals allow-popups-to-escape-sandbox";d.setAttribute("allowfullscreen","true");d.src=b;d.name=a;c.appendChild(d);childWindows.push(d.contentWindow);childWindowsTabs.set(d.contentWindow,c);focusTab(c)})}
function updateDummyTabs(){childTabs.forEach(function(a,b){if(a.dummy){var c=childTabs[b+1];a.tabtitlebar.style.display=c&&c.path===a.path&&c.title===a.title?"none":""}})}openWindow();openTab("/Apps/firetext/",{dummy:!0});openTab("/Apps/strut/",{dummy:!0});var hashArgumentOpenApp=airborn.top_location.hash.match(/[#&;]open=([^&;]+)/),firstApp=hashArgumentOpenApp?"/Apps/"+hashArgumentOpenApp[1].replace(/[./]/g,"")+"/":airborn_localStorage.lastApp||"/Apps/firetext/";
openTab(firstApp,{after:"/Apps/firetext/"===firstApp?childTabs[0]:null});function switchTab(a){childDiv.querySelectorAll(".tabs .tab.focused, .tabtitlebar.focused").forEach(function(a){return a.classList.remove("focused")});a.classList.add("focused");a.tabtitlebar.classList.add("focused");airborn.core.setTitle(a.tabtitlebar.textContent.replace("\u00a0",""))}function focusTab(a){a.querySelector("iframe").focus()}window.addEventListener("scroll",function(){window.scrollTo(0,0)});
