var blockElementNames="address article aside audio blockquote body canvas center dd dir div dl dt fieldset figcaption figure footer form frame frameset h1 h2 h3 h4 h5 h6 header hgroup hr html main menu nav noframes noscript ol output p pre section table tbody td tfoot thead tr ul video".replace(/ /g,",");Node.prototype.closest=function(){return this.parentElement.closest.apply(this.parentElement,arguments)};
function randId(a){var c=(16777215*Math.random()).toString(16);return a?c.split(".").pop():c}var userId=randId(!0);function getLockElement(a){return a.closest(blockElementNames)}function setElementCollabIDs(){var a=new Map;Array.prototype.forEach.call(document.querySelectorAll(blockElementNames.replace("html,","").replace("body,","")),function(c){!c.hasAttribute("collab-id")||a.has(c.getAttribute("collab-id"))?c.setAttribute("collab-id","c"+randId()):a.set(c.getAttribute("collab-id"),!0)})}var shadowDocument;
function elementPath(a){for(var c=[];a.parentElement;){if(a.hasAttribute&&a.hasAttribute("collab-id"))c.push(a.getAttribute("collab-id"));else{for(var b=-1,d=a;d;)d=d.previousSibling,b++;c.push(b)}a=a.parentElement}return c.reverse()}function elementFromPath(a,c,b){for(var d=(c||document).documentElement,e=0;d&&e<a.length;e++)if(d=isFinite(a[e])?d.childNodes[a[e]]:(c||document).querySelector('[collab-id="'+a[e]+'"]'),!d&&b)return elementFromPath(a.slice(0,-1),c);return d}var locks={};
function setLock(a){locks[a.el]=a;elementFromPath(a.el).setAttribute("contenteditable",a.uid===userId)}function getClosestLock(a,c){for(a=a.slice();;a.pop()){if(locks[a]&&locks[a].uid===c)return locks[a];if(!a.length)break}}window.recordSelection=function(){var a=document.getSelection();if(!a.rangeCount)return null;a=a.getRangeAt(0);return{startEl:elementPath(a.startContainer),startOffset:a.startOffset,endEl:elementPath(a.endContainer),endOffset:a.endOffset}};
window.setSelection=function(a){if(a){var c=recordSelection(),b=document.getSelection();if(!c||a.startOffset!==c.startOffset||a.endOffset!==c.endOffset||a.startEl.length!==c.startEl.length||a.endEl.length!==c.endEl.length||a.startEl.some(function(a,b){return a!==c.startEl[b]})||a.endEl.some(function(a,b){return a!==c.endEl[b]})){var d=document.createRange(),e=elementFromPath(a.startEl,document,!0),f=elementFromPath(a.endEl,document,!0);d.setStart(e,Math.min(a.startOffset,"length"in e?e.length:e.childNodes.length));
d.setEnd(f,Math.min(a.endOffset,"length"in f?f.length:f.childNodes.length));b.removeAllRanges();b.addRange(d)}else d=b.getRangeAt(0);document.activeElement&&"keepKeyboardOpenTextarea"===document.activeElement.id&&(b.focusNode.closest('[contenteditable="false"] [contenteditable="true"], html').focus(),b.removeAllRanges(),b.addRange(d));(a=document.getElementById("keepKeyboardOpenTextarea"))&&a.value&&(d.insertNode(document.createTextNode(a.value)),a.value="")}};
window.recordScroll=function(){var a=document.getSelection();if(!a.rangeCount)return null;a=a.getRangeAt(0).getBoundingClientRect();return a.left||a.top?{selectionLeft:a.left,selectionTop:a.top}:null};window.setScroll=function(a){var c=recordScroll();a&&c&&window.scrollBy(c.selectionLeft-a.selectionLeft,c.selectionTop-a.selectionTop)};
function keepKeyboardOpen(){var a=document.getElementById("keepKeyboardOpenTextarea");a||(a=document.createElement("textarea"),a.id="keepKeyboardOpenTextarea",a.setAttribute("_firetext_remove",""),a.setAttribute("style","position: fixed; top: 0; left: -9999px"),document.documentElement.appendChild(a));a.focus()}
function checkLocks(){Array.prototype.forEach.call(document.querySelectorAll('html[contenteditable="false"], html [contenteditable]'),function(a){if(!(locks[elementPath(a)]||"A"===a.nodeName&&document.documentElement.hasAttribute("_firetext_ctrl_held"))){var c=recordSelection(),b=recordScroll();keepKeyboardOpen();a===document.documentElement?a.setAttribute("contenteditable","true"):a.removeAttribute("contenteditable");a.hasAttribute("collab-tmp-lock")&&a.removeAttribute("collab-tmp-lock");setSelection(c);
setScroll(b)}})}function getAttributes(a){var c={};[].slice.call(a.attributes).forEach(function(a){"contenteditable"!==a.name&&(c[a.name]=a.value)});return c}function setAttributes(a,c){[].slice.call(a.attributes).forEach(function(b){c.hasOwnProperty||a.removeAttribute(b.name)});Object.keys(c).forEach(function(b){a.setAttribute(b,c[b])})}
function recordEdit(a,c,b,d){a||(a=document);c||(c=shadowDocument.cloneNode(!0));if(!b){var e=a.getSelection();e.rangeCount&&(b=e.getRangeAt(0).commonAncestorContainer);b&&b!==a.documentElement||(b=a.body)}for(;;b=b.parentElement){if(b===a.documentElement)throw Error("Couldn't construct applyable edit.");b=getLockElement(b);e={el:elementPath(b),html:getElementInnerHTML(b),ts:Date.now(),len:-1!==["html","body"].indexOf(b.nodeName.toLowerCase())?1E3:1E4,uid:userId};d&&(e.check=!0);b===a.body&&(e.parentAttrs=
getAttributes(b.parentElement));applyEdit(e,c);if(b.hasAttribute("collab-added"))b.removeAttribute("collab-added");else if(getHTML(c)===getHTML(a))return e}}function applyEdit(a,c){var b=elementFromPath(a.el,c);b&&(a.hasOwnProperty("html")&&b.innerHTML!==a.html&&(b.innerHTML=a.html),a.hasOwnProperty("attrs")&&setAttributes(b,a.attrs),a.hasOwnProperty("parentAttrs")&&setAttributes(b.parentElement,a.parentAttrs))}
function throttle(a,c){var b,d;return function f(){b?d=!0:(a.apply(this,arguments),d=!1,b=setTimeout(function(a){b=null;d&&f.apply(this,a)},c,arguments))}}function debounce(a,c){var b;return function(){b&&clearTimeout(b);b=setTimeout(function(c){b=null;a.apply(this,c)},c,arguments)}}function checkDocWithPeers(){sendEdit(recordEdit(shadowDocument,shadowDocument,shadowDocument.body,!0))}
var checkDocWithPeersDebounced=debounce(function(){0===Object.keys(locks).filter(function(a){return!locks[a].tmp&&!locks[a].check}).length&&checkDocWithPeers()},2E4);function sendEdit(a){var c=randId(!0);parentMessageProxy.postMessage({command:"collab-message",type:"edit",data:{edit:a,id:c,len:a.len}});collabMessages[c]=a;setLock(a)}
var collabMessages={},onInput=function(a){if("fromCollab"!==a.detail){setElementCollabIDs();var c;try{document.getSelection().getRangeAt(0).commonAncestorContainer.normalize()}catch(b){}try{c=recordEdit()}catch(d){throw document.execCommand("undo"),d;}sendEdit(c)}},checkLocksInterval;parentMessageProxy.registerMessageHandler(function(a){shadowDocument=document.cloneNode(!0);document.addEventListener("input",onInput);checkLocksInterval=setInterval(checkLocks,100)},"collab-enable");
parentMessageProxy.registerMessageHandler(function(a){document.removeEventListener("input",onInput);clearInterval(checkLocksInterval)},"collab-disable");
parentMessageProxy.registerMessageHandler(function(a){var c=a.data.type;a=a.data.data;if("lock-end"===c){var b=collabMessages[a.id];delete collabMessages[a.id];b&&b===locks[b.el]&&(locks[b.el].check||checkDocWithPeersDebounced(),delete locks[b.el])}else if("open"===c)checkDocWithPeers();else if("edit"===c&&(!locks[a.edit.el]||a.edit.uid===locks[a.edit.el].uid||a.edit.ts<locks[a.edit.el].ts||locks[a.edit.el].tmp||locks[a.edit.el].check))if(elementFromPath(a.edit.el)){if(a.edit.uid!==userId){var b=
recordEdit(),d=recordSelection(),e=recordScroll();keepKeyboardOpen();collabMessages[a.id]=a.edit;setLock(a.edit);b&&!getClosestLock(b.el,userId)&&!locks[b.el]&&elementFromPath(a.edit.el).contains(elementFromPath(b.el))&&(b.tmp=!0,setLock(b),elementFromPath(b.el).setAttribute("collab-tmp-lock",""))}applyEdit(a.edit,shadowDocument);if(a.edit.uid!==userId){recordEdit(shadowDocument,document,elementFromPath(a.edit.el,shadowDocument));var f;b&&(f=getClosestLock(b.el,userId))&&!f.tmp&&applyEdit(b);Object.keys(locks).forEach(function(a){var b=
elementFromPath(a.split(","));b&&locks[a]&&(b.setAttribute("contenteditable",locks[a].uid===userId),locks[a].tmp&&b.setAttribute("collab-tmp-lock",""))});setSelection(d);setScroll(e);document.dispatchEvent(new CustomEvent("input",{detail:"fromCollab"}))}}else console.warn("Element doesn't exist")},"collab-message");
