function fixupDocument(a){if(0===document.body.children.length)if(".txt"===filetype)document.body.appendChild(document.createElement("br"));else{var b=document.createElement("p");b.appendChild(document.createElement("br"));document.body.appendChild(b)}if(".odt"===filetype)try{odtdoc.setHTML(getHTML())}catch(c){document.execCommand("undo"),a&&a.stopImmediatePropagation()}document.body.lastElementChild&&"p"===document.body.lastElementChild.nodeName.toLowerCase()&&"false"===document.body.lastElementChild.getAttribute("contenteditable")&&
(b=document.createElement("p"),b.setAttribute("collab-added",""),b.appendChild(document.createElement("br")),document.body.appendChild(b),setElementCollabIDs());document.documentElement.style.getPropertyValue("--width")||document.documentElement.style.setProperty("--width","US"===user_location.country?"8.5in":"21cm");document.documentElement.style.getPropertyValue("--height")||document.documentElement.style.setProperty("--height","US"===user_location.country?"11in":"29.7cm");document.documentElement.style.getPropertyValue("--margin")||
document.documentElement.style.setProperty("--margin","1in")}parentMessageProxy.setSend(parent);parentMessageProxy.setRecv(window);readOnly||(document.documentElement.contentEditable="true",document.execCommand("enableObjectResizing",!1,"true"));document.execCommand("styleWithCSS",!1,!0);".txt"!==filetype&&document.execCommand("defaultParagraphSeparator",!1,"p");
if(0===document.getElementsByTagName("style").length){var style=document.createElement("style");style.textContent="h1 {\n  font-size: 1.5em;\n  margin: 0;\n}\nh2 {\n  font-size: 1.17em;\n  margin: 0;\n}\nh3 {\n  font-size: 1em;\n  margin: 0;\n}\nh4 {\n  font-size: 1em;\n  font-weight: normal;\n  text-decoration: underline;\n  margin: 0;\n}\nh5 {\n  font-size: 1em;\n  color: #555;\n  margin: 0;\n}\nh6 {\n  font-size: 1em;\n  font-weight: normal;\n  text-decoration: underline;\n  color: #444;\n  margin: 0;\n}\np {\n  margin: 0;\n}\nblockquote {\n  margin: 0px 0px 0px 40px;\n}\ntable.default {\n  border-collapse: collapse;\n}\ntable.default, table.default td {\n  border: 1px solid black;\n}\na:link, a:visited {\n  color: #0000ee;\n}\nhr {\n  border: none;\n  border-bottom: 1px solid black;\n}";document.head.appendChild(style)}
readOnly||(window.addEventListener("focus",function(a){parentMessageProxy.postMessage({command:"focus",focus:!0})}),window.addEventListener("blur",function(a){parentMessageProxy.postMessage({command:"focus",focus:!1})}));function updateToolbar(){parentMessageProxy.postMessage({command:"update-toolbar"})}
document.addEventListener("keypress",function(a){if((a.ctrlKey||a.metaKey)&&!a.shiftKey){if(98===a.which)format("bold");else if(105===a.which)format("italic");else if(117===a.which)format("underline");else if(13===a.which||10===a.which){document.execCommand("insertHTML",!1,'<hr class="page-break">');var b=document.getSelection();if(b.anchorOffset&&"HR"===b.anchorNode.childNodes[b.anchorOffset-1].nodeName&&(!b.anchorNode.childNodes[b.anchorOffset]||b.anchorNode.childNodes[b.anchorOffset].nodeType!==
Node.ELEMENT_NODE)){var c=document.createElement("p");c.appendChild(document.createElement("br"));b.anchorNode.appendChild(c)}}else return;a.preventDefault();updateToolbar()}});document.addEventListener("keydown",function(a){9===a.which&&(a.shiftKey?document.execCommand("outdent"):document.execCommand("indent"),a.preventDefault(),updateToolbar())});function isFrame(a){return"IMG"===a.nodeName||"DIV"===a.nodeName&&a.classList.contains("_firetext_frame")}document.addEventListener("click",onFrameClick);
document.addEventListener("contextmenu",onFrameClick);function onFrameClick(a){if(isFrame(a.target)||"HR"===a.target.nodeName){var b=document.createRange();b.selectNode(a.target);document.getSelection().removeAllRanges();document.getSelection().addRange(b)}}var isMac="Mac"===navigator.platform.substr(0,3),ctrlKeyCodes=isMac?[91,93,224]:[17];document.addEventListener("keydown",function(a){-1!==ctrlKeyCodes.indexOf(a.keyCode)&&document.documentElement.setAttribute("_firetext_ctrl_held","")});
document.addEventListener("keyup",function(a){-1!==ctrlKeyCodes.indexOf(a.keyCode)&&document.documentElement.removeAttribute("_firetext_ctrl_held")});document.addEventListener("mousedown",function(a){if("A"===a.target.nodeName){if(!document.documentElement.hasAttribute("_firetext_ctrl_held"))if(isMac?a.metaKey:a.ctrlKey)document.documentElement.setAttribute("_firetext_ctrl_held","");else return;a.target.setAttribute("contenteditable","false")}});window.mousePressed=0;
document.addEventListener("mousedown",function(){window.mousePressed++});document.addEventListener("mouseup",function(){window.mousePressed--;navigator.userAgent.includes("Chrome")&&updateToolbar()});document.addEventListener("input",fixupDocument);fixupDocument();initNight(document,parentMessageProxy);initPrintView(document,parentMessageProxy);initWordCount(document,parentMessageProxy);initColorPickerView(document,parentMessageProxy);
function getSelectedFrame(){var a=document.getSelection();if(!a.rangeCount)return null;a=a.getRangeAt(0);if(a.startContainer===a.endContainer&&a.startContainer.nodeType===Element.ELEMENT_NODE&&1===a.endOffset-a.startOffset&&isFrame(a.startContainer.childNodes[a.startOffset]))return a.startContainer.childNodes[a.startOffset]}
function format(a,b){var c=document.getSelection(),e=!1;if(/[^ ] $/.test(c)&&c.setBaseAndExtent&&c.modify){var d=c.getRangeAt(0);c.setBaseAndExtent(d.startContainer,d.startOffset,d.endContainer,d.endOffset);c.modify("extend","backward","character");e=!0}if("createLink"===a||"unlink"===a)d=c.getRangeAt(0),(d=d.commonAncestorContainer.closest("a"))&&c.selectAllChildren(d);document.execCommand(a,!1,b);e&&c.modify("extend","forward","character")}
parentMessageProxy.registerMessageHandler(function(a){if("justify"===a.data.sCmd.substr(0,7)){var b=getSelectedFrame();b?(b.style.float=b.style.display=b.style.marginLeft=b.style.marginRight=b.style.marginBottom="","justifyLeft"===a.data.sCmd||"justifyRight"===a.data.sCmd?(b.style.float="justifyLeft"===a.data.sCmd?"left":"right",b.style["justifyLeft"===a.data.sCmd?"marginRight":"marginLeft"]="10px",b.style.marginBottom="5px"):"justifyCenter"===a.data.sCmd&&(b.style.display="block",b.style.marginLeft=
b.style.marginRight="auto")):format(a.data.sCmd,a.data.sValue);updateToolbar()}else["superscript","subscript"].includes(a.data.sCmd)?(document.execCommand("styleWithCSS",!1,!1),format(a.data.sCmd,a.data.sValue),document.execCommand("styleWithCSS",!1,!0)):format(a.data.sCmd,a.data.sValue)},"format");
parentMessageProxy.registerMessageHandler(function(a){var b=randId();document.execCommand("insertHTML",!1,['<div class="_firetext_frame" style="\nfloat: left;\nmargin-right: 10px;\nmargin-bottom: 5px;\nborder: 1px solid black;\npadding: 5px;\nwidth: 300px;\n">\n <div class="_firetext_frame_contents">','   <p id="'+b+'"><br></p>'," </div>\n</div>"].join("\n"));a=document.getSelection();a.removeAllRanges();var c=document.createRange(),b=document.getElementById(b);c.setStart(b,0);c.setEnd(b,0);a.addRange(c);
b.removeAttribute("id")},"insert-text-frame");
function getHTML(a){var b=(a||document).doctype;return(b?"<!DOCTYPE "+b.name+(b.publicId?' PUBLIC "'+b.publicId+'"':"")+(!b.publicId&&b.systemId?" SYSTEM":"")+(b.systemId?' "'+b.systemId+'"':"")+">":"")+(a||document).documentElement.outerHTML.replace(/<([a-z]+)[^>]*_firetext_remove=""[^>]*>[^<>]*(?:<\/\1>)?/g,"").replace(/ _firetext_[a-z_]+=""/g,"").replace(/ contenteditable="(?:true|false)"/g,"").replace(/<p[^>]+collab-added=""[^>]+><br><\/p>(<\/body>)/,"$1").replace(/ collab[-a-z]*="[a-z\d.]*"/g,
"").replace(/ spellcheck="(?:true|false)"/,"")}function getElementInnerHTML(a){return a.innerHTML.replace(/ contenteditable="(?:true|false)"/g,"")}document.addEventListener("input",function(){parentMessageProxy.postMessage({command:"doc-changed",html:getHTML(),filetype:filetype})});var getSelectionRange=function(){var a=document.getSelection();return a.rangeCount?a.getRangeAt(0):null},prevRange;
function onSelectionChange(){var a=getSelectionRange();if(a!==prevRange&&(!a||!prevRange||["startContainer","startOffset","endContainer","endOffset"].some(function(b){return a[b]!==prevRange[b]}))&&(updateToolbar(),a&&a.collapsed)){var b;a.startContainer.childNodes[a.startOffset-1]&&"HR"===a.startContainer.childNodes[a.startOffset-1].nodeName?b=a.startContainer.childNodes[a.startOffset-1].nextElementSibling:a.startContainer.childNodes[a.startOffset]&&"HR"===a.startContainer.childNodes[a.startOffset].nodeName&&
(b=a.startContainer.childNodes[a.startOffset].nextElementSibling);b&&a.setStart(b.firstChild&&"BR"!==b.firstChild.nodeName?b.firstChild:b,0)}prevRange=a}document.addEventListener("selectionchange",throttle(onSelectionChange,100));"onselectionchange"in document||setInterval(onSelectionChange,100);
