(function(F){"object"===typeof exports&&"undefined"!==typeof module?module.exports=F():"function"===typeof define&&define.amd?define([],F):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).estraverse=F()})(function(){return function D(p,t,G){function C(q,x){if(!t[q]){if(!p[q]){var m="function"==typeof require&&require;if(!x&&m)return m(q,!0);if(l)return l(q,!0);m=Error("Cannot find module '"+q+"'");throw m.code="MODULE_NOT_FOUND",m;}m=t[q]=
{exports:{}};p[q][0].call(m.exports,function(m){var l=p[q][1][m];return C(l?l:m)},m,m.exports,D,p,t,G)}return t[q].exports}for(var l="function"==typeof require&&require,H=0;H<G.length;H++)C(G[H]);return C}({1:[function(D,p,t){(function C(l){function p(a){var b={},e,d;for(e in a)a.hasOwnProperty(e)&&(d=a[e],b[e]="object"===typeof d&&null!==d?p(d):d);return b}function q(a,b){var e,d,g,f;d=a.length;for(g=0;d;)e=d>>>1,f=g+e,b(a[f])?d=e:(g=f+1,d-=e+1);return g}function x(a,b){this.parent=a;this.key=b}
function m(a,b,e,d){this.node=a;this.path=b;this.wrap=e;this.ref=d}function h(){}function t(a){return null==a?!1:"object"===typeof a&&"string"===typeof a.type}function I(a,b){return(new h).traverse(a,b)}function M(a,b){var e;e=q(b,function(d){return d.range[0]>a.range[0]});a.extendedRange=[a.range[0],a.range[1]];e!==b.length&&(a.extendedRange[1]=b[e].range[0]);--e;0<=e&&(a.extendedRange[0]=b[e].range[1]);return a}var z,A,u,J,L,K,r,v,w;(A=Array.isArray)||(A=function(a){return"[object Array]"===Object.prototype.toString.call(a)});
L=Object.create||function(){function a(){}return function(b){a.prototype=b;return new a}}();K=Object.keys||function(a){var b=[],e;for(e in a)b.push(e);return b};z={AssignmentExpression:"AssignmentExpression",AssignmentPattern:"AssignmentPattern",ArrayExpression:"ArrayExpression",ArrayPattern:"ArrayPattern",ArrowFunctionExpression:"ArrowFunctionExpression",AwaitExpression:"AwaitExpression",BlockStatement:"BlockStatement",BinaryExpression:"BinaryExpression",BreakStatement:"BreakStatement",CallExpression:"CallExpression",
CatchClause:"CatchClause",ClassBody:"ClassBody",ClassDeclaration:"ClassDeclaration",ClassExpression:"ClassExpression",ComprehensionBlock:"ComprehensionBlock",ComprehensionExpression:"ComprehensionExpression",ConditionalExpression:"ConditionalExpression",ContinueStatement:"ContinueStatement",DebuggerStatement:"DebuggerStatement",DirectiveStatement:"DirectiveStatement",DoWhileStatement:"DoWhileStatement",EmptyStatement:"EmptyStatement",ExportAllDeclaration:"ExportAllDeclaration",ExportDefaultDeclaration:"ExportDefaultDeclaration",
ExportNamedDeclaration:"ExportNamedDeclaration",ExportSpecifier:"ExportSpecifier",ExpressionStatement:"ExpressionStatement",ForStatement:"ForStatement",ForInStatement:"ForInStatement",ForOfStatement:"ForOfStatement",FunctionDeclaration:"FunctionDeclaration",FunctionExpression:"FunctionExpression",GeneratorExpression:"GeneratorExpression",Identifier:"Identifier",IfStatement:"IfStatement",ImportDeclaration:"ImportDeclaration",ImportDefaultSpecifier:"ImportDefaultSpecifier",ImportNamespaceSpecifier:"ImportNamespaceSpecifier",
ImportSpecifier:"ImportSpecifier",Literal:"Literal",LabeledStatement:"LabeledStatement",LogicalExpression:"LogicalExpression",MemberExpression:"MemberExpression",MetaProperty:"MetaProperty",MethodDefinition:"MethodDefinition",ModuleSpecifier:"ModuleSpecifier",NewExpression:"NewExpression",ObjectExpression:"ObjectExpression",ObjectPattern:"ObjectPattern",Program:"Program",Property:"Property",RestElement:"RestElement",ReturnStatement:"ReturnStatement",SequenceExpression:"SequenceExpression",SpreadElement:"SpreadElement",
Super:"Super",SwitchStatement:"SwitchStatement",SwitchCase:"SwitchCase",TaggedTemplateExpression:"TaggedTemplateExpression",TemplateElement:"TemplateElement",TemplateLiteral:"TemplateLiteral",ThisExpression:"ThisExpression",ThrowStatement:"ThrowStatement",TryStatement:"TryStatement",UnaryExpression:"UnaryExpression",UpdateExpression:"UpdateExpression",VariableDeclaration:"VariableDeclaration",VariableDeclarator:"VariableDeclarator",WhileStatement:"WhileStatement",WithStatement:"WithStatement",YieldExpression:"YieldExpression"};
J={AssignmentExpression:["left","right"],AssignmentPattern:["left","right"],ArrayExpression:["elements"],ArrayPattern:["elements"],ArrowFunctionExpression:["params","body"],AwaitExpression:["argument"],BlockStatement:["body"],BinaryExpression:["left","right"],BreakStatement:["label"],CallExpression:["callee","arguments"],CatchClause:["param","body"],ClassBody:["body"],ClassDeclaration:["id","superClass","body"],ClassExpression:["id","superClass","body"],ComprehensionBlock:["left","right"],ComprehensionExpression:["blocks",
"filter","body"],ConditionalExpression:["test","consequent","alternate"],ContinueStatement:["label"],DebuggerStatement:[],DirectiveStatement:[],DoWhileStatement:["body","test"],EmptyStatement:[],ExportAllDeclaration:["source"],ExportDefaultDeclaration:["declaration"],ExportNamedDeclaration:["declaration","specifiers","source"],ExportSpecifier:["exported","local"],ExpressionStatement:["expression"],ForStatement:["init","test","update","body"],ForInStatement:["left","right","body"],ForOfStatement:["left",
"right","body"],FunctionDeclaration:["id","params","body"],FunctionExpression:["id","params","body"],GeneratorExpression:["blocks","filter","body"],Identifier:[],IfStatement:["test","consequent","alternate"],ImportDeclaration:["specifiers","source"],ImportDefaultSpecifier:["local"],ImportNamespaceSpecifier:["local"],ImportSpecifier:["imported","local"],Literal:[],LabeledStatement:["label","body"],LogicalExpression:["left","right"],MemberExpression:["object","property"],MetaProperty:["meta","property"],
MethodDefinition:["key","value"],ModuleSpecifier:[],NewExpression:["callee","arguments"],ObjectExpression:["properties"],ObjectPattern:["properties"],Program:["body"],Property:["key","value"],RestElement:["argument"],ReturnStatement:["argument"],SequenceExpression:["expressions"],SpreadElement:["argument"],Super:[],SwitchStatement:["discriminant","cases"],SwitchCase:["test","consequent"],TaggedTemplateExpression:["tag","quasi"],TemplateElement:[],TemplateLiteral:["quasis","expressions"],ThisExpression:[],
ThrowStatement:["argument"],TryStatement:["block","handler","finalizer"],UnaryExpression:["argument"],UpdateExpression:["argument"],VariableDeclaration:["declarations"],VariableDeclarator:["id","init"],WhileStatement:["test","body"],WithStatement:["object","body"],YieldExpression:["argument"]};r={};v={};w={};u={Break:r,Skip:v,Remove:w};x.prototype.replace=function(a){this.parent[this.key]=a};x.prototype.remove=function(){if(A(this.parent))return this.parent.splice(this.key,1),!0;this.replace(null);
return!1};h.prototype.path=function(){function a(a,c){if(A(c))for(d=0,g=c.length;d<g;++d)a.push(c[d]);else a.push(c)}var b,e,d,g,f,c;if(!this.__current.path)return null;f=[];b=2;for(e=this.__leavelist.length;b<e;++b)c=this.__leavelist[b],a(f,c.path);a(f,this.__current.path);return f};h.prototype.type=function(){return this.current().type||this.__current.wrap};h.prototype.parents=function(){var a,b,e;e=[];a=1;for(b=this.__leavelist.length;a<b;++a)e.push(this.__leavelist[a].node);return e};h.prototype.current=
function(){return this.__current.node};h.prototype.__execute=function(a,b){var e,d;d=void 0;e=this.__current;this.__current=b;this.__state=null;a&&(d=a.call(this,b.node,this.__leavelist[this.__leavelist.length-1].node));this.__current=e;return d};h.prototype.notify=function(a){this.__state=a};h.prototype.skip=function(){this.notify(v)};h.prototype["break"]=function(){this.notify(r)};h.prototype.remove=function(){this.notify(w)};h.prototype.__initialize=function(a,b){this.visitor=b;this.root=a;this.__worklist=
[];this.__leavelist=[];this.__fallback=this.__state=this.__current=null;"iteration"===b.fallback?this.__fallback=K:"function"===typeof b.fallback&&(this.__fallback=b.fallback);this.__keys=J;if(b.keys){var e=L(this.__keys),d=b.keys,g=K(d),f,c,k;c=0;for(k=g.length;c<k;c+=1)f=g[c],e[f]=d[f];this.__keys=e}};h.prototype.traverse=function(a,b){var e,d,g,f,c,k,E,y,l,n,h;this.__initialize(a,b);h={};e=this.__worklist;d=this.__leavelist;e.push(new m(a,null,null,null));for(d.push(new m(null,null,null,null));e.length;)if(g=
e.pop(),g===h){if(g=d.pop(),f=this.__execute(b.leave,g),this.__state===r||f===r)break}else if(g.node){f=this.__execute(b.enter,g);if(this.__state===r||f===r)break;e.push(h);d.push(g);if(this.__state!==v&&f!==v){f=g.node;c=f.type||g.wrap;l=this.__keys[c];if(!l)if(this.__fallback)l=this.__fallback(f);else throw Error("Unknown node type "+c+".");for(E=l.length;0<=--E;)if(k=l[E],n=f[k])if(A(n))for(y=n.length;0<=--y;){if(n[y]){if(c!==z.ObjectExpression&&c!==z.ObjectPattern||"properties"!==l[E])if(t(n[y]))g=
new m(n[y],[k,y],null,null);else continue;else g=new m(n[y],[k,y],"Property",null);e.push(g)}}else t(n)&&e.push(new m(n,k,null,null))}}};h.prototype.replace=function(a,b){function e(a){var c,b,e;if(a.ref.remove())for(c=a.ref.key,e=a.ref.parent,a=d.length;a--;)if(b=d[a],b.ref&&b.ref.parent===e){if(b.ref.key<c)break;--b.ref.key}}var d,g,f,c,k,l,h,p,n,q,u,B;this.__initialize(a,b);q={};d=this.__worklist;g=this.__leavelist;u={root:a};k=new m(a,null,null,new x(u,"root"));d.push(k);for(g.push(k);d.length;)if(k=
d.pop(),k===q){if(k=g.pop(),c=this.__execute(b.leave,k),void 0!==c&&c!==r&&c!==v&&c!==w&&k.ref.replace(c),this.__state!==w&&c!==w||e(k),this.__state===r||c===r)break}else{c=this.__execute(b.enter,k);void 0!==c&&c!==r&&c!==v&&c!==w&&(k.ref.replace(c),k.node=c);if(this.__state===w||c===w)e(k),k.node=null;if(this.__state===r||c===r)break;if(f=k.node)if(d.push(q),g.push(k),this.__state!==v&&c!==v){c=f.type||k.wrap;p=this.__keys[c];if(!p)if(this.__fallback)p=this.__fallback(f);else throw Error("Unknown node type "+
c+".");for(l=p.length;0<=--l;)if(B=p[l],n=f[B])if(A(n))for(h=n.length;0<=--h;){if(n[h]){if(c!==z.ObjectExpression&&c!==z.ObjectPattern||"properties"!==p[l])if(t(n[h]))k=new m(n[h],[B,h],null,new x(n,h));else continue;else k=new m(n[h],[B,h],"Property",new x(n,h));d.push(k)}}else t(n)&&d.push(new m(n,B,null,new x(f,B)))}}return u.root};l.version=D("./package.json").version;l.Syntax=z;l.traverse=I;l.replace=function(a,b){return(new h).replace(a,b)};l.attachComments=function(a,b,e){var d=[],g,f,c;if(!a.range)throw Error("attachComments needs range information");
if(!e.length){if(b.length){f=0;for(g=b.length;f<g;f+=1)e=p(b[f]),e.extendedRange=[0,a.range[0]],d.push(e);a.leadingComments=d}return a}f=0;for(g=b.length;f<g;f+=1)d.push(M(p(b[f]),e));c=0;I(a,{enter:function(a){for(var b;c<d.length;){b=d[c];if(b.extendedRange[1]>a.range[0])break;b.extendedRange[1]===a.range[0]?(a.leadingComments||(a.leadingComments=[]),a.leadingComments.push(b),d.splice(c,1)):c+=1}if(c===d.length)return u.Break;if(d[c].extendedRange[0]>a.range[1])return u.Skip}});c=0;I(a,{leave:function(a){for(var b;c<
d.length;){b=d[c];if(a.range[1]<b.extendedRange[0])break;a.range[1]===b.extendedRange[0]?(a.trailingComments||(a.trailingComments=[]),a.trailingComments.push(b),d.splice(c,1)):c+=1}if(c===d.length)return u.Break;if(d[c].extendedRange[0]>a.range[1])return u.Skip}});return a};l.VisitorKeys=J;l.VisitorOption=u;l.Controller=h;l.cloneEnvironment=function(){return C({})};return l})(t)},{"./package.json":2}],2:[function(D,p,t){p.exports={name:"estraverse",description:"ECMAScript JS AST traversal functions",
homepage:"https://github.com/estools/estraverse",main:"estraverse.js",version:"4.2.0",engines:{node:">=0.10.0"},maintainers:[{name:"Yusuke Suzuki",email:"utatane.tea@gmail.com",web:"http://github.com/Constellation"}],repository:{type:"git",url:"http://github.com/estools/estraverse.git"},devDependencies:{"babel-preset-es2015":"^6.3.13","babel-register":"^6.3.13",chai:"^2.1.1",espree:"^1.11.0",gulp:"^3.8.10","gulp-bump":"^0.2.2","gulp-filter":"^2.0.0","gulp-git":"^1.0.1","gulp-tag-version":"^1.2.1",
jshint:"^2.5.6",mocha:"^2.1.0"},license:"BSD-2-Clause",scripts:{test:"npm run-script lint && npm run-script unit-test",lint:"jshint estraverse.js","unit-test":"mocha --compilers js:babel-register"}}},{}]},{},[1])(1)});
