(function(){function f(a){this.stream="";JSZip.support.uint8array&&a instanceof Uint8Array?this.stream=JSZip.utils.uint8Array2String(a):JSZip.support.arraybuffer&&a instanceof ArrayBuffer?(a=new Uint8Array(a),this.stream=JSZip.utils.uint8Array2String(a)):this.stream=JSZip.utils.string2binary(a);this.index=0}function h(a,b){this.options=a;this.loadOptions=b}function k(a,b){this.files=[];this.loadOptions=b;a&&this.load(a)}var g=function(a){var b="",c,d;for(d=0;d<(a||"").length;d++)c=a.charCodeAt(d),
b+="\\x"+(16>c?"0":"")+c.toString(16).toUpperCase();return b};f.prototype={checkOffset:function(a){this.checkIndex(this.index+a)},checkIndex:function(a){if(this.stream.length<a||0>a)throw Error("End of stream reached (stream length = "+this.stream.length+", asked index = "+a+"). Corrupted zip ?");},setIndex:function(a){this.checkIndex(a);this.index=a},skip:function(a){this.setIndex(this.index+a)},byteAt:function(a){return this.stream.charCodeAt(a)},readInt:function(a){var b=0,c;this.checkOffset(a);
for(c=this.index+a-1;c>=this.index;c--)b=(b<<8)+this.byteAt(c);this.index+=a;return b},readString:function(a){this.checkOffset(a);var b=this.stream.slice(this.index,this.index+a);this.index+=a;return b},readDate:function(){var a=this.readInt(4);return new Date((a>>25&127)+1980,(a>>21&15)-1,a>>16&31,a>>11&31,a>>5&63,(a&31)<<1)}};h.prototype={isEncrypted:function(){return 1===(this.bitFlag&1)},useUTF8:function(){return 2048===(this.bitFlag&2048)},readLocalPart:function(a){var b,c;a.skip(22);this.fileNameLength=
a.readInt(2);c=a.readInt(2);this.fileName=a.readString(this.fileNameLength);a.skip(c);if(-1==this.compressedSize||-1==this.uncompressedSize)throw Error("Bug or corrupted zip : didn't get enough informations from the central directory (compressedSize == -1 || uncompressedSize == -1)");this.compressedFileData=a.readString(this.compressedSize);a:{a=this.compressionMethod;for(b in JSZip.compressions)if(JSZip.compressions.hasOwnProperty(b)&&JSZip.compressions[b].magic===a){b=JSZip.compressions[b];break a}b=
null}if(null===b)throw Error("Corrupted zip : compression "+g(this.compressionMethod)+" unknown (inner file : "+this.fileName+")");this.uncompressedFileData=b.uncompress(this.compressedFileData);if(this.uncompressedFileData.length!==this.uncompressedSize)throw Error("Bug : uncompressed data size mismatch");if(this.loadOptions.checkCRC32&&JSZip.prototype.crc32(this.uncompressedFileData)!==this.crc32)throw Error("Corrupted zip : CRC32 mismatch");},readCentralPart:function(a){this.versionMadeBy=a.readString(2);
this.versionNeeded=a.readInt(2);this.bitFlag=a.readInt(2);this.compressionMethod=a.readString(2);this.date=a.readDate();this.crc32=a.readInt(4);this.compressedSize=a.readInt(4);this.uncompressedSize=a.readInt(4);this.fileNameLength=a.readInt(2);this.extraFieldsLength=a.readInt(2);this.fileCommentLength=a.readInt(2);this.diskNumberStart=a.readInt(2);this.internalFileAttributes=a.readInt(2);this.externalFileAttributes=a.readInt(4);this.localHeaderOffset=a.readInt(4);if(this.isEncrypted())throw Error("Encrypted zip are not supported");
this.fileName=a.readString(this.fileNameLength);this.readExtraFields(a);this.parseZIP64ExtraField(a);this.fileComment=a.readString(this.fileCommentLength);this.dir=this.externalFileAttributes&16?!0:!1},parseZIP64ExtraField:function(a){this.extraFields[1]&&(a=new f(this.extraFields[1].value),-1===this.uncompressedSize&&(this.uncompressedSize=a.readInt(8)),-1===this.compressedSize&&(this.compressedSize=a.readInt(8)),-1===this.localHeaderOffset&&(this.localHeaderOffset=a.readInt(8)),-1===this.diskNumberStart&&
(this.diskNumberStart=a.readInt(4)))},readExtraFields:function(a){var b=a.index,c,d,e;for(this.extraFields=this.extraFields||{};a.index<b+this.extraFieldsLength;)c=a.readInt(2),d=a.readInt(2),e=a.readString(d),this.extraFields[c]={id:c,length:d,value:e}},handleUTF8:function(){this.useUTF8()&&(this.fileName=JSZip.prototype.utf8decode(this.fileName),this.fileComment=JSZip.prototype.utf8decode(this.fileComment))}};k.prototype={checkSignature:function(a){var b=this.reader.readString(4);if(b!==a)throw Error("Corrupted zip or bug : unexpected signature ("+
g(b)+", expected "+g(a)+")");},readBlockEndOfCentral:function(){this.diskNumber=this.reader.readInt(2);this.diskWithCentralDirStart=this.reader.readInt(2);this.centralDirRecordsOnThisDisk=this.reader.readInt(2);this.centralDirRecords=this.reader.readInt(2);this.centralDirSize=this.reader.readInt(4);this.centralDirOffset=this.reader.readInt(4);this.zipCommentLength=this.reader.readInt(2);this.zipComment=this.reader.readString(this.zipCommentLength)},readBlockZip64EndOfCentral:function(){this.zip64EndOfCentralSize=
this.reader.readInt(8);this.versionMadeBy=this.reader.readString(2);this.versionNeeded=this.reader.readInt(2);this.diskNumber=this.reader.readInt(4);this.diskWithCentralDirStart=this.reader.readInt(4);this.centralDirRecordsOnThisDisk=this.reader.readInt(8);this.centralDirRecords=this.reader.readInt(8);this.centralDirSize=this.reader.readInt(8);this.centralDirOffset=this.reader.readInt(8);this.zip64ExtensibleData={};for(var a=this.zip64EndOfCentralSize-44,b,c,d;0<a;)b=this.reader.readInt(2),c=this.reader.readInt(4),
d=this.reader.readString(c),this.zip64ExtensibleData[b]={id:b,length:c,value:d}},readBlockZip64EndOfCentralLocator:function(){this.diskWithZip64CentralDirStart=this.reader.readInt(4);this.relativeOffsetEndOfZip64CentralDir=this.reader.readInt(8);this.disksCount=this.reader.readInt(4);if(1<this.disksCount)throw Error("Multi-volumes zip are not supported");},readLocalFiles:function(){var a,b;for(a=0;a<this.files.length;a++)b=this.files[a],this.reader.setIndex(b.localHeaderOffset),this.checkSignature(JSZip.signature.LOCAL_FILE_HEADER),
b.readLocalPart(this.reader),b.handleUTF8()},readCentralDir:function(){var a;for(this.reader.setIndex(this.centralDirOffset);this.reader.readString(4)===JSZip.signature.CENTRAL_FILE_HEADER;)a=new h({zip64:this.zip64},this.loadOptions),a.readCentralPart(this.reader),this.files.push(a)},readEndOfCentral:function(){var a=this.reader.stream.lastIndexOf(JSZip.signature.CENTRAL_DIRECTORY_END);if(-1===a)throw Error("Corrupted zip : can't find end of central directory");this.reader.setIndex(a);this.checkSignature(JSZip.signature.CENTRAL_DIRECTORY_END);
this.readBlockEndOfCentral();if(65535===this.diskNumber||65535===this.diskWithCentralDirStart||65535===this.centralDirRecordsOnThisDisk||65535===this.centralDirRecords||-1===this.centralDirSize||-1===this.centralDirOffset){this.zip64=!0;a=this.reader.stream.lastIndexOf(JSZip.signature.ZIP64_CENTRAL_DIRECTORY_LOCATOR);if(-1===a)throw Error("Corrupted zip : can't find the ZIP64 end of central directory locator");this.reader.setIndex(a);this.checkSignature(JSZip.signature.ZIP64_CENTRAL_DIRECTORY_LOCATOR);
this.readBlockZip64EndOfCentralLocator();this.reader.setIndex(this.relativeOffsetEndOfZip64CentralDir);this.checkSignature(JSZip.signature.ZIP64_CENTRAL_DIRECTORY_END);this.readBlockZip64EndOfCentral()}},load:function(a){this.reader=new f(a);this.readEndOfCentral();this.readCentralDir();this.readLocalFiles()}};JSZip.prototype.load=function(a,b){var c,d,e;b=b||{};b.base64&&(a=JSZipBase64.decode(a));c=(new k(a,b)).files;for(d=0;d<c.length;d++)e=c[d],this.file(e.fileName,e.uncompressedFileData,{binary:!0,
optimizedBinaryString:!0,date:e.date,dir:e.dir});return this}})();
